### ISSUE TITLE
hello i am getting this error

### ISSUE THREAD

**Issue by ex725** [modul8co/hikvision-nvr-events#2]
hello i am getting this error

[1/25/2022, 11:39:33] [Hikvision NVR Events] Could not load channels TypeError: Cannot read property 'forEach' of undefined
    at /usr/local/lib/node_modules/@modul8co/homebridge-hikvision-nvr-events/src/platform.ts:58:60
    at Parser.<anonymous> (/usr/local/lib/node_modules/@modul8co/homebridge-hikvision-nvr-events/node_modules/xml2js/lib/parser.js:304:18)
    at Parser.emit (events.js:315:20)
    at SAXParser.onclosetag (/usr/local/lib/node_modules/@modul8co/homebridge-hikvision-nvr-events/node_modules/xml2js/lib/parser.js:262:26)
    at emit (/usr/local/lib/node_modules/@modul8co/homebridge-hikvision-nvr-events/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/usr/local/lib/node_modules/@modul8co/homebridge-hikvision-nvr-events/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/usr/local/lib/node_modules/@modul8co/homebridge-hikvision-nvr-events/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/usr/local/lib/node_modules/@modul8co/homebridge-hikvision-nvr-events/node_modules/sax/lib/sax.js:1436:13)
    at Parser.exports.Parser.Parser.parseString (/usr/local/lib/node_modules/@modul8co/homebridge-hikvision-nvr-events/node_modules/xml2js/lib/parser.js:323:31)
    at Parser.parseString (/usr/local/lib/node_modules/@modul8co/homebridge-hikvision-nvr-events/node_modules/xml2js/lib/parser.js:5:59)

**Comment by ex725** [comment]
Now I get this error when it detects motion

[1/25/2022, 11:56:35] [Hikvision NVR Events] Could not activate motion for channel Arka SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at /usr/local/lib/node_modules/@modul8co/homebridge-hikvision-nvr-events/src/platform.ts:74:32
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at HikvisionNVREventsPlatform.motionUpdater (/usr/local/lib/node_modules/@modul8co/homebridge-hikvision-nvr-events/src/platform.ts:73:7)

**Comment by modul8co** [comment]
Hey, so I take it your first issue was resolved? I assume you had it on DVR mode (or the opposite) and you amended that to resolve the first issue?

Regarding the second issue, I assume you have a camera called 'Arka'. Please check that it's called Arka in FFMPEG.

Then, please navigate to http://[Your Homebridge IP]:8080/motion?Arka

For example, for me - the URL would be http://192.168.1.135:8080/motion?Arka

Please let me know what response you get. Please note: for this plugin to work, FFMPEG must be configured to allow motion activation over HTTP, and you must have a corresponding camera name in FFMPEG.

Cheers

**Comment by ex725** [comment]
greetings again

I wanted to add screenshots, I hope it will be more descriptive

![image](https://user-images.githubusercontent.com/56446241/150968929-1fe6cd83-8282-4d03-89f3-d7d29663d01f.png)
![image](https://user-images.githubusercontent.com/56446241/150969026-50e7a466-0bfe-4179-ac9b-b66d7076b150.png)
![image](https://user-images.githubusercontent.com/56446241/150969154-5b9a5e56-55bc-4581-837f-2bc2580c8eb3.png)
![image](https://user-images.githubusercontent.com/56446241/150969193-323cc24e-d1ce-4a80-93a6-07c2e9f55762.png)
![image](https://user-images.githubusercontent.com/56446241/150969393-ef4388a0-f80b-4876-a46c-382329ee77a9.png)

**Comment by ex725** [comment]
I solved the problem dude

I wrote the dvr ip address here

![image](https://user-images.githubusercontent.com/56446241/150969670-54a0187a-8cf1-41a2-afe5-f70aceb48171.png)

**Comment by modul8co** [comment]
Your motion URL should be http://192.168.0.35:8080/motion

Right now, you're pointing motion events to your DVR, which wont trigger the cameras in FFMPEG to show motion.

**Comment by modul8co** [comment]
If 192.168.0.35 is the IP address of your Homebridge on which this plugin is running, you could also just leave the default (http://localhost:8080/motion)

**Comment by ex725** [comment]
Thank you for your help. everything works properly

There are constant notifications due to snowfall.

Is there a solution on this

![image](https://user-images.githubusercontent.com/56446241/150978835-a1ed8039-9c2c-40f3-934c-e712a4146d8e.png)

**Comment by modul8co** [comment]
Great news!

Can you disable the motion detection for this camera to verify that it's motion detection triggering this? With sensitivity 0 I wouldn't have expected snow to trigger it.

Perhaps another motion event is firing (one with greater sensitivity, eg video loss, video tampering etc).

**Comment by ex725** [comment]
Motion detection warning comes in hikvision app.
I'll try turning off everything else except the motion notification

**Comment by modul8co** [comment]
OK, if it's a motion detection warning, I don't know what we could do to stop it.

In my experience, reducing the sensitivity and/or defining the zone has stopped problems like this. The most you can do with Homekit is control when you receive the notifications (eg when you're not at home, between certain times etc). 

The other thing you can do is set a longer cool off period in FFMPEG (time between motion detections).

**Comment by ex725** [comment]
I decided to turn off notifications until the snow is gone :)

But the system works flawlessly.
